export const GET_CUSTOMERS_REQUEST = "GET_CUSTOMERS_REQUEST";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAIL = "GET_CUSTOMERS_FAIL";

export const GET_CUSTOMER_REQUEST = "GET_CUSTOMER_REQUEST";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAIL = "GET_CUSTOMER_FAIL";

export const GET_ANIMAL_REQUEST = "GET_ANIMAL_REQUEST";
export const GET_ANIMAL_SUCCESS = "GET_ANIMAL_SUCCESS";
export const GET_ANIMAL_FAIL = "GET_ANIMAL_FAIL";

export const EDIT_CUSTOMER_REQUEST = "EDIT_CUSTOMER_REQUEST";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_FAIL = "EDIT_CUSTOMER_FAIL";

export const EDIT_ANIMAL_REQUEST = "EDIT_ANIMAL_REQUEST";
export const EDIT_ANIMAL_SUCCESS = "EDIT_ANIMAL_SUCCESS";
export const EDIT_ANIMAL_FAIL = "EDIT_ANIMAL_FAIL";

export const CREATE_RECORD_REQUEST = "CREATE_RECORD_REQUEST";
export const CREATE_RECORD_SUCCESS = "CREATE_RECORD_SUCCESS";
export const CREATE_RECORD_FAIL = "CREATE_RECORD_FAIL";

export const SEARCH_RECORD_REQUEST = "SEARCH_RECORD_REQUEST";
export const SEARCH_RECORD_SUCCESS = "SEARCH_RECORD_SUCCESS";
export const SEARCH_RECORD_FAIL = "SEARCH_RECORD_FAIL";
export const SEARCH_RECORD_RESET = "SEARCH_RECORD_RESET";

export const GET_RECORD_REQUEST = "GET_RECORD_REQUEST";
export const GET_RECORD_SUCCESS = "GET_RECORD_SUCCESS";
export const GET_RECORD_FAIL = "GET_RECORD_FAIL";

export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";

export const DELETE_ANIMAL_REQUEST = "DELETE_ANIMAL_REQUEST";
export const DELETE_ANIMAL_SUCCESS = "DELETE_ANIMAL_SUCCESS";
export const DELETE_ANIMAL_FAIL = "DELETE_ANIMAL_FAIL";