export const STAFF_LOGIN_REQUEST = "STAFF_LOGIN_REQUEST";
export const STAFF_LOGIN_SUCCESS = "STAFF_LOGIN_SUCCESS";
export const STAFF_LOGIN_FAIL = "STAFF_LOGIN_FAIL";

export const STAFF_DELETE_REQUEST = "STAFF_DELETE_REQUEST";
export const STAFF_DELETE_SUCCESS = "STAFF_DELETE_SUCCESS";
export const STAFF_DELETE_FAIL = "STAFF_DELETE_FAIL";

export const STAFF_LOGOUT = "STAFF_LOGOUT";

export const STAFF_SHOW_REQUEST = "STAFF_SHOW_REQUEST";
export const STAFF_SHOW_SUCCESS = "STAFF_SHOW_SUCCESS";
export const STAFF_SHOW_FAIL = "STAFF_SHOW_FAIL";

export const CREATE_STAFF_REQUEST = "CREATE_STAFF_REQUEST";
export const CREATE_STAFF_SUCCESS = "CREATE_STAFF_SUCCESS";
export const CREATE_STAFF_FAIL = "CREATE_STAFF_FAIL";